#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App1.Resource", IsApplication=true)]

namespace App1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int BreakAnimation = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int cyan = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int dump = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Green1 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Green2 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Green3 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int green_image1 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int green_image2 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int green_image3 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int grey = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int H1 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int H2 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int H3 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int HB1 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int HB2 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Health_Check = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int Icon = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int IIS = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ImageAnimation = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int lavender = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int light_green_image = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int Logo = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int N1 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int Notification = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int red_button = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int restart = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int rotation = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int settings = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int settings1 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int settings10 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int settings11 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int settings12 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int settings13 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int settings14 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int settings15 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int settings16 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int settings17 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int settings18 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int settings19 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int settings2 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int settings20 = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int settings21 = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int settings3 = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int settings4 = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int settings5 = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int settings6 = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int settings7 = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int settings8 = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int settings9 = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int Stetes1 = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int webRequest = 2130837555;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060021
			public const int CPU2 = 2131099681;
			
			// aapt resource value: 0x7f060001
			public const int NetDispatcherAppPool = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int animateImage = 2131099655;
			
			// aapt resource value: 0x7f060024
			public const int btn1 = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int btn2 = 2131099685;
			
			// aapt resource value: 0x7f06001d
			public const int cpuDesc = 2131099677;
			
			// aapt resource value: 0x7f06000b
			public const int dump = 2131099659;
			
			// aapt resource value: 0x7f06000f
			public const int dumpdesc = 2131099663;
			
			// aapt resource value: 0x7f06001b
			public const int graphLayoutCPU = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int graphLayoutCPUChild = 2131099676;
			
			// aapt resource value: 0x7f060011
			public const int graphLayoutMemory = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int graphLayoutMemoryChild = 2131099666;
			
			// aapt resource value: 0x7f060016
			public const int imageView1 = 2131099670;
			
			// aapt resource value: 0x7f060020
			public const int imageView2 = 2131099680;
			
			// aapt resource value: 0x7f060018
			public const int layoutlegend2 = 2131099672;
			
			// aapt resource value: 0x7f060014
			public const int legendVerticalLayout = 2131099668;
			
			// aapt resource value: 0x7f06001e
			public const int legendVerticalLayout2 = 2131099678;
			
			// aapt resource value: 0x7f060003
			public const int linearLayout1 = 2131099651;
			
			// aapt resource value: 0x7f060008
			public const int linearLayout3 = 2131099656;
			
			// aapt resource value: 0x7f06000c
			public const int linearLayout4 = 2131099660;
			
			// aapt resource value: 0x7f060015
			public const int linearLayout5 = 2131099669;
			
			// aapt resource value: 0x7f06001f
			public const int linearLayout6 = 2131099679;
			
			// aapt resource value: 0x7f060010
			public const int mainGraphLayout = 2131099664;
			
			// aapt resource value: 0x7f060017
			public const int memeory1 = 2131099671;
			
			// aapt resource value: 0x7f060019
			public const int memeory2 = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int memeory3 = 2131099674;
			
			// aapt resource value: 0x7f060013
			public const int memoryDesc = 2131099667;
			
			// aapt resource value: 0x7f06000a
			public const int recycle = 2131099658;
			
			// aapt resource value: 0x7f06000e
			public const int recycledesc = 2131099662;
			
			// aapt resource value: 0x7f060002
			public const int settingsBtn = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int simpleSpinnerItem = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int spinnerSite = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int stetescope = 2131099648;
			
			// aapt resource value: 0x7f060022
			public const int txt = 2131099682;
			
			// aapt resource value: 0x7f060005
			public const int txtAppPoolName = 2131099653;
			
			// aapt resource value: 0x7f060023
			public const int txtTime = 2131099683;
			
			// aapt resource value: 0x7f060009
			public const int webrequest = 2131099657;
			
			// aapt resource value: 0x7f06000d
			public const int webrequestdesc = 2131099661;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int settings = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int ApplicationPools = 2130968578;
			
			// aapt resource value: 0x7f040009
			public const int CPUDesc = 2130968585;
			
			// aapt resource value: 0x7f04000e
			public const int CPUText1 = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int CPUText2 = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int CPUText3 = 2130968592;
			
			// aapt resource value: 0x7f040003
			public const int DefaultAppPool = 2130968579;
			
			// aapt resource value: 0x7f040007
			public const int DumpDesc = 2130968583;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040008
			public const int MemoryDesc = 2130968584;
			
			// aapt resource value: 0x7f04000b
			public const int MemoryText1 = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int MemoryText2 = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int MemoryText3 = 2130968589;
			
			// aapt resource value: 0x7f040004
			public const int NetDispatcherPool = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int RecycleDesc = 2130968582;
			
			// aapt resource value: 0x7f04000a
			public const int Site = 2130968586;
			
			// aapt resource value: 0x7f040005
			public const int WebRequestDesc = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int button_text = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
